export const contacts = {
  general: 'info@korasb.com', procurement: 'procurement@korasb.com', contracts: 'contracts@korasb.com',
  phone: '609-469-6366', phoneHref: 'tel:+16094696366', location: 'Princeton, New Jersey 08540',
} as const;
export const site = { name: 'Kora Business Solutions', status: 'Government Registered Supplier', contacts };
export const navigation = [ ['What We Do', '/what-we-do'], ['Products', '/products'], ['Government', '/government'], ['Partners', '/partners'], ['Insights', '/insights'], ['About', '/about'] ] as const;
export const contentApproval = { status: 'unapproved', owner: null, source: 'PRODUCT_REQUIREMENTS.md', reviewedAt: null, purpose: 'Development preview; detailed capability copy, categories, operating process, and privacy policy require approval before publication.' } as const;
export const capabilities = [
 { slug: 'sourcing-procurement', title: 'Sourcing & Procurement', verb: 'Source', type: 'product', description: 'Turn a product specification into a focused sourcing conversation.', examples: ['A defined product specification and target quantity', 'An alternative to a difficult-to-source item', 'A procurement need that spans several categories'], role: 'Discuss the requirement, identify the information needed to evaluate it, and establish an appropriate next step.', prompt: 'Bring the specification. Start the conversation.', related: ['supply-distribution', 'logistics-trade'] },
 { slug: 'supply-distribution', title: 'Supply & Distribution', verb: 'Supply', type: 'product', description: 'Frame the product, quantity, destination, and timing behind a supply requirement.', examples: ['A recurring supply requirement', 'A multi-location delivery requirement', 'A defined purchasing or replenishment need'], role: 'Clarify supply requirements and coordination needs. Availability, price, and lead time must be confirmed for each inquiry.', prompt: 'Make the supply requirement clear.', related: ['sourcing-procurement', 'logistics-trade'] },
 { slug: 'medical-invasive-technologies', title: 'Medical & Invasive Technologies', verb: 'Specify', type: 'medical', description: 'Start a business-focused discussion about medical and invasive technology sourcing requirements.', examples: ['A non-patient-specific equipment specification', 'A business procurement requirement for medical technology', 'Questions about a proposed product category'], role: 'Receive business and procurement requirements for review. Specific products, sourcing scope, and authorization claims require approval and confirmation.', prompt: 'Start with the business requirement.', related: ['sourcing-procurement', 'supply-distribution'] },
 { slug: 'iot-connected-systems', title: 'IoT & Connected Systems', verb: 'Connect', type: 'iot', description: 'Define what needs to connect, what it should help achieve, and the operating constraints.', examples: ['A connected-device sourcing requirement', 'A high-level sensor or telemetry use case', 'An operational need involving connected equipment'], role: 'Clarify the intended business outcome and the scope that needs evaluation. Compatibility, security, and support arrangements require specific validation.', prompt: 'Connect the requirement to the outcome.', related: ['technology-enablement', 'sourcing-procurement'] },
 { slug: 'business-services', title: 'Business Services', verb: 'Operate', type: 'service', description: 'Give an operational need a clear scope, owner, and next step.', examples: ['A business process coordination requirement', 'A need for specialist service-provider involvement', 'A cross-functional operational requirement'], role: 'Understand the desired business outcome and identify the scope and relationships that need to be discussed.', prompt: 'Describe the work that needs to move.', related: ['technology-enablement', 'logistics-trade'] },
 { slug: 'technology-enablement', title: 'Technology Enablement', verb: 'Enable', type: 'technology', description: 'Put the business requirement at the center of a technology discussion.', examples: ['A workflow that needs technology support', 'A technology-hardware procurement requirement', 'A defined operational integration question'], role: 'Frame the operational objective, current constraints, and expertise needed to assess a practical path forward.', prompt: 'Begin with the operational objective.', related: ['iot-connected-systems', 'business-services'] },
 { slug: 'logistics-trade', title: 'Logistics & Trade Coordination', verb: 'Move', type: 'logistics', description: 'Bring movement, destinations, and coordination requirements into one conversation.', examples: ['A product-movement requirement with defined destinations', 'A delivery-coordination need involving multiple parties', 'A trade-related requirement needing further scoping'], role: 'Discuss the movement requirement and the parties, timing, and information needed to evaluate coordination. Specific services and responsibilities must be confirmed.', prompt: 'Define where the requirement needs to go.', related: ['supply-distribution', 'business-services'] },
].map(item => ({ ...item, approval: contentApproval }));
export const productCategories = [
 ['Industrial', 'Components, materials, and operational requirements'], ['Scientific & Laboratory', 'Business procurement for scientific environments'], ['Medical Technologies', 'Non-patient-specific technology requirements'], ['Medical & Invasive Technologies', 'Business sourcing discussions requiring scope approval'], ['IoT & Connected Devices', 'Connected equipment and device requirements'], ['Facilities', 'Building and workplace supply requirements'], ['Janitorial', 'Cleaning and maintenance supply requirements'], ['Technology Hardware', 'Hardware requirements for business operations'], ['Electronics', 'Electronic components and equipment requirements'], ['Machinery', 'Machinery specifications and procurement needs'], ['Safety', 'Workplace safety product requirements'], ['Packaging', 'Packaging materials and supply requirements'], ['General Merchandise', 'Cross-category product inquiries'], ['Agricultural', 'Agricultural supply requirements'], ['Specialized Procurement', 'Requirements outside standard categories'],
].map(([title, description]) => ({title, description, approval: contentApproval}));
export interface Insight { title: string; slug: string; summary: string; publishDate: string; updatedDate?: string; topic: string; body: string; seoTitle: string; seoDescription: string; socialImage: string; published: boolean; relatedHref: string; relatedLabel: string; }
export const insights: Insight[] = [];
export const publishedInsights = insights.filter(item => item.published);
